ShopSphere/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include
from . import views,user_login

admin.site.site_header = "ShopSphere Admin"
admin.site.site_title = "ShopSphere Admin Portal"
admin.site.index_title = "Welcome to ShopSphere Portal"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('base/', views.BASE,name="base"),
    path('', views.HOME,name="home"),
    path('contact/', views.CONTACT,name="contact"),
    path('shop/', views.SHOP,name="shop"),
    path('shop/<slug>',views.DETAIL_PRODUCT,name='detail_product'),
    path('accounts/cart/', views.CART,name="cart"),
    path('accounts/cart/add', user_login.ADDCART,name="add-cart"),
    path('accounts/cart/remove/<id>', user_login.REMOVECART,name="remove-cart"),
    path('accounts/cart/update/<action>/<id>', user_login.UPDATEQTY,name="update-quantity"),

    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/register', user_login.REGISTER,name="register"),
    path('accounts/create-account', user_login.CREATEACCOUNT,name="create-account"),
    path('dologin/', user_login.LOGIN,name="dologin"),
    path('logout/',user_login.LOGOUT,name='logout'),

    path('accounts/profile', user_login.PROFILE,name="profile"),
    path('accounts/profile/update', user_login.PROFILEUPDATE,name="profileupdate"),
    path('accounts/checkout', views.CHECKOUT,name='checkout'),
    path('accounts/order', user_login.ORDER,name='order'),
    path('accounts/order/create', user_login.CREATEORDER,name='create-order'),

    path('search/',views.SEARCH,name='search'),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app/models.py
from itertools import product
from math import prod
import os
from uuid import uuid4
from django.db import models
from distutils.command.upload import upload
from django.contrib.auth.models import User
from autoslug import AutoSlugField

class Category(models.Model):
    image = models.ImageField(upload_to="categories",null=True)
    title = models.CharField(max_length=200,null=True)

    def __str__(self):
        return self.title
    
class Product(models.Model):

    sts = (
        ("PUBLISH","PUBLISH"),
        ("DRAFT","DRAFT"),
    )
    category = models.ForeignKey(Category,on_delete=models.CASCADE,null=True,blank=True)
    image = models.ImageField(upload_to="products",null=True,blank=True)
    title = models.CharField(max_length=200,null=True)
    description = models.TextField()
    price = models.IntegerField(null=True,default=0)
    discount = models.IntegerField(null=True,default=0)
    stock = models.IntegerField(null=True,default=0)
    date = models.DateTimeField(auto_now_add=True)
    slug = AutoSlugField(populate_from='title',unique=True,null=True,default=None)
    status = models.CharField(choices=sts,null=True,max_length=200)

    def __str__(self):
        return self.title
    
class Cart(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity = models.IntegerField(null=True,blank=True)

    def __str__(self):
        return self.user.username+" - "+self.product.title


class Address(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    street = models.CharField(null=True,max_length=200)
    pin = models.IntegerField(null=True)
    subdistrict = models.CharField(null=True,max_length=200)
    district = models.CharField(null=True,max_length=200)
    state = models.CharField(null=True,max_length=200)
    def __str__(self):
        return self.user.username

class Order(models.Model):
    sts = (
        ("PENDING","PENDING"),
        ("CANCEL","CANCEL"),
        ("SHIPPING","SHIPPING"),
        ("SHIPED","SHIPED"),
    )
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    total = models.IntegerField(null=True,default=0)
    orderdate = models.DateTimeField(auto_now_add=True)
    shipdate = models.DateField()
    status = models.CharField(choices=sts,max_length=200,null=True,blank=True)

    def __str__(self):
        return self.user.username+' '+str(self.total)

class OrderItem(models.Model):
    
    order = models.ForeignKey(Order,on_delete=models.CASCADE,null=True)
    product = models.ForeignKey(Product,on_delete=models.CASCADE,null=True)
    total = models.IntegerField(null=True,default=0)
    quantity = models.IntegerField(null=True,default=0)

    def __str__(self):
        return self.order.user.username+' '+self.product.title+' '+self.order.status

ShopSphere/views.py
from ast import Dict
from math import prod
from unicodedata import category
from django.shortcuts import render,redirect
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from app.models import *

def BASE(request):
          
    return render(request,"base.html")

def HOME(request):

    category = Category.objects.all().order_by('id')[:10]
    product = Product.objects.filter(status="PUBLISH").order_by('-id')[:20]
    
    data = {
        'category':category,
        'product':product,
    }

    return render(request,"home.html", data)

def CONTACT(request):
    category = Category.objects.all().order_by('id')[:10]
    data = {
        'category':category
    }
    return render(request,"contact.html",data)

def SHOP(request):

    category = Category.objects.all().order_by('id')[:10]
    product = Product.objects.filter(status="PUBLISH").order_by('-id')[:100]
    discount_product = Product.objects.filter(discount__gte=10).order_by('-id')[:10]
    data = {
        'category':category,
        'product':product,
        'disProduct':discount_product
    }

    return render(request,"shop-grid.html", data)

def DETAIL_PRODUCT(request,slug):
    product = Product.objects.filter(slug=slug)
    if product.exists():
        category = Category.objects.get(id=product.first().category.id)
        relatedProduct = Product.objects.filter(category=category)[:20]
        # print(relatedProduct)
        data = {
            'product':product.first,
            'relatedProduct':relatedProduct
        }
        print(data)
        return render(request,"shop-details.html",data)
    else:
        return redirect('home')

@login_required
def CART(request):
    cart = Cart.objects.filter(user=request.user)
    category = Category.objects.all().order_by('id')[:10]
    data = {
        'cart':cart,
        'category':category
    }
    return render(request,"shop-cart.html",data)

@login_required
def CHECKOUT(request):
    cart = Cart.objects.filter(user=request.user)
    add = Address.objects.filter(user=request.user)
    category = Category.objects.all().order_by('id')[:10]
    data = {
        'cart':cart,
        'category':category,
        'add':add.first()
    }
    return render(request,"checkout.html",data)

def SEARCH(request):
    
    search = request.GET.get('search')
    category = request.GET.get('cat')
    data={
        'title':search
    }
    if search != None:
        data['product'] = Product.objects.filter(title__icontains=search)
    else:
        if category != None:
            cat = Category.objects.filter(id=category)
            if cat.exists():
                data['title'] = category=cat.first().title
                data['product'] = Product.objects.filter(category=cat.first())

    return render(request,'search.html',data)

app/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
<!DOCTYPE html>
<html lang="zxx">

<head>

    {% load static %}

    <meta charset="UTF-8">
    <meta name="description" content="Ogani Template">
    <meta name="keywords" content="Ogani, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ShopSphere - {% block title %}{% endblock title %}</title>


    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">

    
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>


    {% include "common/header.html" %}

    {% block content %}
    
    {% endblock content %}

    {% include "common/footer.html" %}

    <!-- Js Plugins -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'js/mixitup.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

</body>

</html>

templates/checkout.html
{% extends 'base.html' %}
{% block title %}Checkout{% endblock title %}
{% block content %}
{% load static %}
{% load filterData %}

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="/static/img/breadcrumb.png">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>Checkout</h2>
                        <div class="breadcrumb__option">
                            <a href="./index.html">Home</a>
                            <span>Checkout</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Checkout Section Begin -->
    <section class="checkout spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h6><span class="icon_tag_alt"></span> Have a coupon? <a href="#">Click here</a> to enter your code
                    </h6>
                </div>
            </div>
            <div class="checkout__form">
                <h4>Billing Details</h4>
                <form action="#">
                    <div class="row">
                        <div class="col-lg-8 col-md-6">
                            <div class="row">
                        	
                        		<div class="col-lg-6 my-2 row"><span class="col-6 font-weight-bold">Firstname</span> <span>{{user.first_name}}</span> </div>
                        		<div class="col-lg-6 my-2 row"><span class="col-6 font-weight-bold">Lastname</span> <span>{{user.last_name}}</span> </div>
                        		<div class="col-lg-6 my-2 row"><span class="col-6 font-weight-bold">Email</span> <span>{{user.email}}</span> </div>
                        	</div>
                        	<div class="row">
                        		<div class="col-lg-12 my-2 row"><span class="col-3 font-weight-bold"> Street </span> <span>{{add.street}}</span> </div>
                        		<div class="col-lg-12 my-2 row"><span class="col-3 font-weight-bold"> Sub-District </span> <span>{{add.subdistrict}}</span> </div>
                        		<div class="col-lg-12 my-2 row"><span class="col-3 font-weight-bold"> District </span> <span>{{add.district}}</span> </div>
                        		<div class="col-lg-12 my-2 row"><span class="col-3 font-weight-bold"> State </span> <span>{{add.state}}</span> </div>
                        		<div class="col-lg-12 my-2 row"><span class="col-3 font-weight-bold"> Pin </span> <span>{{add.pin}}</span> </div>
                        		
                        	</div>
                        </div>
                        <div class="col-lg-4 col-md-6">
                            <div class="checkout__order">
                                <h4>Your Order</h4>
                                <div class="checkout__order__products">Products <span>Total</span></div>
                                <ul>
                                    {% for c in user.cart_set.all  %}
                                        <li>{{c.product.title}} <span>${% discount_price c.product.price c.product.discount %}</span></li>
                                    {% endfor %}
                                </ul>
                                {% cartTotal user.cart_set.all as total %}
                                <div class="checkout__order__subtotal">Subtotal <span>${% cartTotal user.cart_set.all %}</span></div>
                                <div class="checkout__order__total">Total <span>${{total}}</span></div>
                                {% if total > 0  %}
                                    <a href="{% url 'create-order' %}" class="site-btn">PLACE ORDER</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
    <!-- Checkout Section End -->
{% endblock content %}

templates/common/footer.html
<!-- Footer Section Begin -->
<footer class="footer spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="footer__about">
                    <div class="footer__about__logo">
                        <!-- <a href="./index.html"><img src="img/logo.png" alt=""></a> -->
                        <h3>ShopSphere</h3>
                    </div>
                    <ul>
                        <li>Address: 60-49 Road 11378 New York</li>
                        <li>Phone: +65 11.188.888</li>
                        <li>Email: hello@colorlib.com</li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-6 offset-lg-1">
                <div class="footer__widget">
                    <ul>
                        <li><a href="{% url 'home' %}">Home</a></li>
                        <li><a href="{% url 'shop' %}">Shop</a></li>
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'profile' %}">Profile</a></li>
                        {% endif %}
                    </ul>
                    {% if user.is_authenticated %}
                        <ul>
                            <li><a href="{% url 'cart' %}">Cart</a></li>
                            <li><a href="{% url 'order' %}">Orders</a></li>
                        </ul>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="footer__copyright">
                    <div class="footer__copyright__text">
                        <p>
                            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- Footer Section End -->

templates/common/header.html
{% load filterData %}

<!-- Humberger Begin -->
<div class="humberger__menu__overlay"></div>
<div class="humberger__menu__wrapper">
    <div class="humberger__menu__logo">
        <!-- <a href="#"><img src="img/logo.png" alt=""></a> -->
        <h3>ShopSphere</h3>
    </div>
    {% if user.is_authenticated %}
        <div class="humberger__menu__cart">
            <ul>
                <li><a href="#"><i class="fa fa-shopping-bag"></i> <span>{{user.cart_set.all.count}}</span></a></li>
            </ul>
            <div class="header__cart__price">item: <span>${% cartTotal user.cart_set.all %}</span></div>
        </div>
    {% endif %}
    {% if not user.is_authenticated %}
        <div class="humberger__menu__widget">
            <div class="header__top__right__auth">
                <a href="{% url 'login' %}"><i class="fa fa-user"></i> Login</a>
            </div>
        </div>
    {% endif %}
    <nav class="humberger__menu__nav mobile-menu">
        <ul>
            {% comment %} class="active" {% endcomment %}
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'shop' %}">Shop</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'profile' %}">{{user.first_name}} {{user.last_name}}</a>
                    <ul class="header__menu__dropdown">
                        <li><a href="{% url 'profile' %}">Profile</a></li>
                        <li><a href="{% url 'cart' %}">Shoping Cart</a></li>
                        <li><a href="{% url 'checkout' %}">Check Out</a></li>
                        <li><a href="{% url 'order' %}">Orders</a></li>
                        <li><a href="{% url 'logout' %}">Logout</a></li>
                    </ul>
                </li>
            {% endif %}
            <li><a href="{% url 'contact' %}">Contact</a></li>
        </ul>
    </nav>
    <div id="mobile-menu-wrap"></div>
    <div class="humberger__menu__contact">
        <ul>
            <li><i class="fa fa-envelope"></i> hello@colorlib.com</li>
        </ul>
    </div>
</div>
<!-- Humberger End -->

<!-- Header Section Begin -->
<header class="header">
    <div class="header__top">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6">
                    <div class="header__top__left">
                        <ul>
                            <li><i class="fa fa-envelope"></i> hello@colorlib.com</li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                    <div class="header__top__right">
                        <div class="header__top__right__auth">
                            {% if not user.is_authenticated %}
                            <a href="{% url 'login' %}"><i class="fa fa-user"></i> Login</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="header__logo">
                    <!-- <a href="./index.html"><img src="img/logo.png" alt=""></a> -->
                    <h3>ShopSphere</h3>
                </div>
            </div>
            <div class="col-lg-6">
                <nav class="header__menu">
                    <ul>
                        {% comment %} class="active" {% endcomment %}
                        <li><a href="{% url 'home' %}">Home</a></li>
                        <li><a href="{% url 'shop' %}">Shop</a></li>
                        {% if user.is_authenticated %}
                        <li><a href="{% url 'profile' %}">{{user.first_name}} {{user.last_name}}</a>
                            <ul class="header__menu__dropdown">
                                <li><a href="{% url 'profile' %}">Profile</a></li>
                                <li><a href="{% url 'cart' %}">Shoping Cart</a></li>
                                <li><a href="{% url 'checkout' %}">Check Out</a></li>
                                <li><a href="{% url 'order' %}">Orders</a></li>
                                <li><a href="{% url 'logout' %}">Logout</a></li>
                            </ul>
                        </li>
                        {% endif %}
                        <li><a href="{% url 'contact' %}">Contact</a></li>
                    </ul>
                </nav>
            </div>
            <div class="col-lg-3">
                {% if user.is_authenticated %}
                    <div class="header__cart">
                        <ul>
                            <li><a href="{% url 'cart' %}"><i class="fa fa-shopping-bag"></i> <span>{{user.cart_set.all.count}}</span></a></li>
                        </ul>
                        <div class="header__cart__price">item: <span>${% cartTotal user.cart_set.all %}</span></div>
                    </div>
                {% endif %}
            </div>
        </div>
        <div class="humberger__open">
            <i class="fa fa-bars"></i>
        </div>
    </div>
</header>
<!-- Header Section End -->

<!-- Hero Section Begin -->
<section class="hero">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="hero__categories">
                    <div class="hero__categories__all">
                        <i class="fa fa-bars"></i>
                        <span>All departments</span>
                    </div>
                    <ul style="display: none;">
                        {% for cat in category  %}
                            <li><a href="/search?cat={{cat.id}}">{{cat.title}}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="hero__search">
                    <div class="hero__search__form">
                        <form method="GET" action="{% url 'search' %}">
                            <input type="text" name="search" placeholder="What do yo u need?">
                            <button type="submit" class="site-btn">SEARCH</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Hero Section End -->

templates/contact.html
{% extends 'base.html' %}
{% block title %}Contact{% endblock title %}
{% block content %}
{% load static %}

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="/static/img/breadcrumb.png">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>Contact Us</h2>
                        <div class="breadcrumb__option">
                            <a href="./index.html">Home</a>
                            <span>Contact Us</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Contact Section Begin -->
    <section class="contact spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-6 text-center">
                    <div class="contact__widget">
                        <span class="icon_phone"></span>
                        <h4>Phone</h4>
                        <p>+01-3-8888-6868</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 text-center">
                    <div class="contact__widget">
                        <span class="icon_pin_alt"></span>
                        <h4>Address</h4>
                        <p>60-49 Road 11378 New York</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 text-center">
                    <div class="contact__widget">
                        <span class="icon_clock_alt"></span>
                        <h4>Open time</h4>
                        <p>10:00 am to 23:00 pm</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 text-center">
                    <div class="contact__widget">
                        <span class="icon_mail_alt"></span>
                        <h4>Email</h4>
                        <p>hello@colorlib.com</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Contact Section End -->

    <!-- Map Begin -->
    <div class="map">
        <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d49116.39176087041!2d-86.41867791216099!3d39.69977417971648!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x886ca48c841038a1%3A0x70cfba96bf847f0!2sPlainfield%2C%20IN%2C%20USA!5e0!3m2!1sen!2sbd!4v1586106673811!5m2!1sen!2sbd"
            height="500" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
        <div class="map-inside">
            <i class="icon_pin"></i>
            <div class="inside-widget">
                <h4>New York</h4>
                <ul>
                    <li>Phone: +12-345-6789</li>
                    <li>Add: 16 Creek Ave. Farmingdale, NY</li>
                </ul>
            </div>
        </div>
    </div>
    <!-- Map End -->

    <!-- Contact Form Begin -->
    <div class="contact-form spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="contact__form__title">
                        <h2>Leave Message</h2>
                    </div>
                </div>
            </div>
            <form action="#">
                <div class="row">
                    <div class="col-lg-6 col-md-6">
                        <input type="text" placeholder="Your name">
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <input type="text" placeholder="Your Email">
                    </div>
                    <div class="col-lg-12 text-center">
                        <textarea placeholder="Your message"></textarea>
                        <button type="submit" class="site-btn">SEND MESSAGE</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <!-- Contact Form End -->
{% endblock content %}

templates/shop-order.html
{% extends 'base.html' %}
{% block title %}Order{% endblock title %}
{% block content %}
{% load static %}
{% load filterData %}

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="/static/img/breadcrumb.png">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>Shopping Orders</h2>
                        <div class="breadcrumb__option">
                            <a href="{% url 'home' %}">Home</a>
                            <span>Shopping Orders</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Shoping Cart Section Begin -->
    <section class="shoping-cart spad">
        <div class="container">
        	<h4 class="my-2">Order Items :</h4>
            <div class="row">
                <div class="col-lg-12 border p-2">
                    {% for o in order  %}
                        
                        <div class="my-2 py-1 row" data-toggle="collapse" data-target="#collapseExample-{{o.id}}" aria-expanded="false" aria-controls="collapseExample-{{o.id}}">
                            
                                <div class="col-4">
                                    <i class="fa fa-eye mx-2"></i> Total Items : {{o.orderitem_set.all.count}}
                                </div>
                                <div class="col-4">
                                    {{o.status}} 
                                </div>
                                <div class="col-4">
                                    $ {{o.total}}
                                </div>
                            </div>
                        <div class="collapse" id="collapseExample-{{o.id}}">
                            <div class="card card-body">
                                <div class="row">
                                    <div class="col-12">
                                        {% for item in o.orderitem_set.all  %}
                                            <div class="row my-1">
                                                <div class="col"> <img src="/media/{{item.product.image}}" width="40"> </div>
                                                <div class="col"> {{item.product.title}}</div>
                                                <div class="col">${% discount_price item.product.price item.product.discount %}</div>
                                                <div class="col"> {{item.quantity}}</div>
                                            </div>
                                        {% endfor %}
                                    </div>
                                    </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
    <!-- Shoping Cart Section End -->
    

{% endblock content %}